sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t testdocker1987/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true testdocker1987/react-test npm test

after_success:
  - docker build -t testdocker1987/multi-client ./client
  - docker build -t testdocker1987/multi-nginx ./nginx
  - docker build -t testdocker1987/multi-server ./server
  - docker build -t testdocker1987/multi-worker ./worker


  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push testdocker1987/multi-client
  - docker push testdocker1987/multi-nginx
  - docker push testdocker1987/multi-server
  - docker push testdocker1987/multi-worker
  
   # deploy:
   # provider: elasticbeanstalk
   # region: 'ap-south-1'                  # subdomain in the urlss
   # app: 'multi-docker'
   # env: 'multidocker-env'
   # bucket_name: 'elasticbeanstalk-ap-south-1-178298393559'
   # bucket_path: 'docker-multi'
  # on:
     # branch: master
   # access_key_id: $aws_access_key
   # secret_access_key: $aws_secret_key
deploy: 
  app: multi-docker
  bucket_name: elasticbeanstalk-ap-south-1-178298393559
  bucket_path: docker-multi
  env: multidocker-env
  provider: elasticbeanstalk
  region: ap-south-1
  true: 
    aws_access_key: $AWS_ACCESS_KEY
    branch: master
    aws_secret_key: $AWS_SECRET_KEY
